### ISSUE TITLE
启动项目报错handshake failed

### ISSUE THREAD

**Issue by huahuayu** [FISCO-BCOS/spring-boot-starter#71]
## 问题描述
我按照readme里面的指引，首先复制了sdk的三个证书文件到resource目录，然后修改了application.yml配置

启动项目报handshake failed错误，message: not an SSL/TLS record

![image](https://user-images.githubusercontent.com/1725060/84119549-1c37e500-aa67-11ea-999e-7ce3db38fb2e.png)

## 版本信息
fisco 2.4.0
国密版

## 重现步骤

** step1: 部署链，使用sdk和链交互**
[全过程步骤记录](https://gist.github.com/huahuayu/c32bb822786a263954649626803d68e8)

**step2: 配置示例springboot sdk项目**
克隆本项目，并将控制台的证书文件拷贝到resource文件夹

![image](https://user-images.githubusercontent.com/1725060/84121908-49d25d80-aa6a-11ea-942f-049df9038c1f.png)

修改application.yml配置  
```
encrypt-type: # 0:standard, 1:guomi
  encrypt-type: 1

group-channel-connections-config:
  caCert: classpath:ca.crt
  sslCert: classpath:sdk.crt
  sslKey: classpath:sdk.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        - 192.168.10.239:9025 # node listen_ip:channel_listen_port
    - group-id: 2
      connections-str:
        - 192.168.10.239:9026 # node listen_ip:channel_listen_port
    - group-id: 3
      connections-str:
        - 192.168.10.239:9027 # node listen_ip:channel_listen_port

channel-service:
  group-id: 1 # The specified group to which the SDK connects
  agency-name: agencyB # agency name

accounts:
  pem-file: 0xcdcce60801c0a2e6bb534322c32ae528b9dec8d2.pem
  p12-file: 0x98333491efac02f8ce109b0c499074d47e7779a6.p12
  password: 123456
```

其中192.168.10.239:9025，9026，9027就是三个群组节点的channel_listen_port  

另外**多问一句**：accounts是干嘛用的？

**step3: 启动项目，报错**
handshake failed错误，message: not an SSL/TLS record

[详细错误日志](https://gist.github.com/huahuayu/a0bb80f9a91e17f27e95808056a25bd3)
